// Auto-generated EKF error parameters from Allan deviation analysis
// Generated by tune.py

#ifndef TUNED_EKF_PARAMS_H
#define TUNED_EKF_PARAMS_H

#include "ekf.h"

inline constexpr EkfErrorParameters SENSE_HAT_DATA_PARAMS = 
{
    .sampling_freq = 52.051289,
    .gyro_x_n = 2.1072071062e-04,
    .gyro_x_b = 1.3405299582e-04,
    .gyro_x_tp = 13.256156,
    .gyro_y_n = 1.8296497951e-04,
    .gyro_y_b = 1.4333840014e-04,
    .gyro_y_tp = 13.256156,
    .gyro_z_n = 1.8989422621e-04,
    .gyro_z_b = 1.5659603614e-04,
    .gyro_z_tp = 24.994578,
    .accel_x_n = 1.1208581747e-03,
    .accel_x_b = 4.3216707585e-04,
    .accel_x_tp = 13.256156,
    .accel_y_n = 9.4322053084e-04,
    .accel_y_b = 5.3190058233e-04,
    .accel_y_tp = 7.031526,
    .accel_z_n = 8.6952763744e-03,
    .accel_z_b = 1.8072688211e-03,
    .accel_z_tp = 30.892606,
    .baro_altitude_n = 1.3389559051e-01,
    .baro_altitude_b = 1.4283838135e-02,
    .baro_altitude_tp = 0.019212,
    .gravity_sigma_x = 3.2984182427e-03,
    .gravity_sigma_y = 2.7756730298e-03,
    .gravity_sigma_z = 2.5588124230e-02,
};

inline constexpr EkfErrorParameters TEENSY_PTYPE_DATA_PARAMS = 
{
    .sampling_freq = 99.927690,
    .gyro_x_n = 2.7455781310e-04,
    .gyro_x_b = 1.5827641254e-05,
    .gyro_x_tp = 316.228665,
    .gyro_y_n = 3.8544165412e-04,
    .gyro_y_b = 1.7538643716e-05,
    .gyro_y_tp = 316.228665,
    .gyro_z_n = 2.6445489328e-04,
    .gyro_z_b = 1.2867393887e-05,
    .gyro_z_tp = 316.228665,
    .accel_x_n = 1.0741458806e-03,
    .accel_x_b = 4.9802246271e-04,
    .accel_x_tp = 316.228665,
    .accel_y_n = 1.2474549610e-03,
    .accel_y_b = 6.8270478848e-04,
    .accel_y_tp = 8.686281,
    .accel_z_n = 1.3914383987e-03,
    .accel_z_b = 7.0496216251e-04,
    .accel_z_tp = 316.228665,
    .baro_altitude_n = 1.8783743686e-02,
    .baro_altitude_b = 8.1489591735e-03,
    .baro_altitude_tp = 0.050000,
    .gravity_sigma_x = 4.3797115342e-03,
    .gravity_sigma_y = 5.0863602233e-03,
    .gravity_sigma_z = 5.6734368339e-03,
};

#endif // TUNED_EKF_PARAMS_H
