# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build-windows-ekf:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Eigen
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz" -OutFile "eigen.tar.gz"
        tar -xzf eigen.tar.gz

    - name: Install Eigen
      run: |
        cd eigen-3.4.0
        mkdir build
        cd build
        cmake ..
        cmake --build . --target install

    - name: Configure CMake (ekf)
      run: cmake -B ${{github.workspace}}/ekf/build -S ${{github.workspace}}/ekf -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON

    - name: Build (ekf)
      run: cmake --build ${{github.workspace}}/ekf/build --config Debug

    - name: Test (ekf)
      working-directory: ${{github.workspace}}/ekf/build
      run: ctest -C Debug

  build-windows-sim:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Eigen
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz" -OutFile "eigen.tar.gz"
        tar -xzf eigen.tar.gz

    - name: Install Eigen
      run: |
        cd eigen-3.4.0
        mkdir build
        cd build
        cmake ..
        cmake --build . --target install

    - name: Configure CMake (sim)
      run: cmake -B ${{github.workspace}}/sim/build -S ${{github.workspace}}/sim -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON

    - name: Build (sim)
      run: cmake --build ${{github.workspace}}/sim/build --config Debug

    - name: Test (sim)
      working-directory: ${{github.workspace}}/sim/build
      run: ctest -C Debug

  build-platformio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ${{github.workspace}}/ekf-teensy
        run: pio run

      - name: Test PlatformIO Project
        working-directory: ${{github.workspace}}/ekf-teensy
        run: pio test --environment native

